// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CodeForFun.Core.Entities;

namespace CodeForFun.Repository.Entities.Concrete
{
    public partial class ProductDetail : IEntity
    {
        public int Id { get; set; }
        [StringLength(256)]
        public string Description { get; set; }

        public int? ProductId { get; set; }
        public virtual Product IdNavigation { get; set; }
    }
}